name: SMS Gateway
version: 1.1.9
#stage: stable
slug: sms_gateway
description: SMS Gateway for MQTT using a usb GSM dongle
#codenotary: helios14_75@hotmail.fr
codenotary: bigthundersr@outlook.com
#url: https://github.com/Helios06/sms_gateway
url: https://github.com/BigThunderSR/sms_gateway
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
#homeassistant_api: true
#supervisor_api: false
#auth_api: false
#ingress: false
init: false
options:
  GSM_Mode: "modem"
  GSM_Device: "/dev/serial/by-id/usb-xxxx"
  GSM_PIN: "-"
  GSM_AUTH: ""
  MQTT_Host: "homeassistant.local"
  MQTT_Port: 1883
  MQTT_User: "mqtt"
  MQTT_Password: "mqtt"
  MQTT_Receive: "sms_received"
  MQTT_Send: "send_sms"
  ADDON_Logging: "INFO"
schema:
  GSM_Mode: str
  GSM_Device: str
  GSM_PIN: str?
  GSM_AUTH: str?
  MQTT_Host: str
  MQTT_Port: int
  MQTT_User: str
  MQTT_Password: password
  MQTT_Receive: str
  MQTT_Send: str
  ADDON_Logging: str
devices:
  - /dev/ttyUSB[0-9]*
  - /dev/ttyACM[0-9]*
  - /dev/serial/by-id/*
